version: '2'

networks:
  rbcnetwork:
    external: true

services:

    web:
        build:
            context: .docker/nginx
        volumes:
            - ./:/var/www:cached
        ports:
            - "80:80"
        extra_hosts:
            - "dockerhost:10.0.75.1"
        networks:
          - rbcnetwork

    app:
        build:
            context: .docker/php
            args:
                PUID: "1000"
                PHP_INSTALL_XDEBUG: "true"
                INSTALL_GIT: "true"
                PHP_XDEBUG_PORT: "9000"
        volumes:
            - ./:/var/www:cached
            - ./.docker/php/xdebug_custom.ini:/usr/local/etc/php/conf.d/55-xdebug.ini
        environment:
            - "PHP_IDE_CONFIG=serverName=localhost"
            - "COMPOSER_MEMORY_LIMIT=-1"
        user: www-data
        extra_hosts:
            - "dockerhost:10.0.75.1"
        networks:
          - rbcnetwork

    database:
        image: postgres
        environment:
            - "POSTGRES_DB=rbc"
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
        ports:
            - "5432:5432"
        volumes:
            - ./:/var/www
        networks:
          - rbcnetwork
